name: Test Quick Start Guide

on:
  push:
    branches:
      - mesharma/quick-start-jupyter
  workflow_dispatch: {}

jobs:
  test-quick-start:
    runs-on:
        group: Fastchecker

    steps:
      - name: ðŸ“¥ Checkout Repository
        uses: actions/checkout@v4

      - name: ðŸ› ï¸ Set Up Python & Jupyter
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: ðŸ“¦ Install Dynamo
        run: |
          pip install ai-dynamo[all]

      - name: âœ… Run Dynamo
        run: |
          dynamo run Qwen/Qwen2.5-3B-Instruct  > output.txt
          pip list | grep dynamo
          cat output.txt
